// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DecryptM(arg1) {
  return window['go']['main']['App']['DecryptM'](arg1);
}

export function DecryptV(arg1, arg2) {
  return window['go']['main']['App']['DecryptV'](arg1, arg2);
}

export function EncryptM(arg1) {
  return window['go']['main']['App']['EncryptM'](arg1);
}

export function EncryptV(arg1, arg2) {
  return window['go']['main']['App']['EncryptV'](arg1, arg2);
}
